/*
SQLyog Ultimate v10.00 Beta1
MySQL - 5.6.10 : Database - darshan
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`darshan` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `darshan`;

/*Table structure for table `login` */

DROP TABLE IF EXISTS `login`;

CREATE TABLE `login` (
  `ID` varchar(50) DEFAULT NULL,
  `FIRSTNAME` varchar(50) DEFAULT NULL,
  `LASTNAME` varchar(50) DEFAULT NULL,
  `EMPLOYEMENTID` varchar(50) DEFAULT NULL,
  `STARTDATE` date DEFAULT NULL,
  `DESIGNATION` varchar(50) DEFAULT NULL,
  `DEPARTMENT` varchar(50) DEFAULT NULL,
  `ENDDATE` date DEFAULT NULL,
  `STATUS` varchar(50) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `REPORTINGMANAGER` varchar(50) DEFAULT NULL,
  `GENDER` varchar(50) DEFAULT NULL,
  `BLOODGROUP` varchar(50) DEFAULT NULL,
  `ADDRESS` varchar(50) DEFAULT NULL,
  `RELATIONSHIP` varchar(50) DEFAULT NULL,
  `INSTITUION` varchar(50) DEFAULT NULL,
  `PERCENTAGE` int(50) DEFAULT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `login` */

insert  into `login`(`ID`,`FIRSTNAME`,`LASTNAME`,`EMPLOYEMENTID`,`STARTDATE`,`DESIGNATION`,`DEPARTMENT`,`ENDDATE`,`STATUS`,`DOB`,`REPORTINGMANAGER`,`GENDER`,`BLOODGROUP`,`ADDRESS`,`RELATIONSHIP`,`INSTITUION`,`PERCENTAGE`,`PASSWORD`) values ('arun','arun','ak','11111',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('jgjsg','ff','gkjdgluy','1233',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('a','a','a','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('Darshan TR','fqfq','Darshanpartha270@gmail.com','6360',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('darshan','qwer','Darshan@','536372',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),('1234',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qwer');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
